### ISSUE TITLE
Implement Narrative Engine v3: Unified Story Format and LLM-First Architecture

### ISSUE THREAD

**Issue by indraastra** [indraastra/iffy#24]
## Overview

Implement the comprehensive Narrative Engine v3 proposal that radically simplifies the Iffy Engine by moving from complex state machines to an LLM-first architecture with minimal, expressive story format.

**Proposal Document**: `docs/proposals/narrative-engine-v3.md`

## Key Changes

- **90% complexity reduction**: 6 core concepts instead of 20+ specialized systems
- **Natural language goals** replace complex state machines  
- **Impromptu endings** for emergent narrative conclusions
- **Universal hints field** for contextual LLM guidance
- **Pure LLM-driven interaction** - eliminates basic commands entirely
- **Character relationships** structured per-character
- **Flexible OR requirements** with nested array syntax

### Phase 1: Core Engine (2 weeks)
- [ ] Create new `NarrativeEngineV3` class alongside existing engine
- [ ] Implement feature flag system for gradual rollout
- [ ] Basic moment/goal/flag processing
- [ ] Impromptu ending detection system
- [ ] Story parser for v3 format

### Phase 2: Advanced Features (2 weeks)  
- [ ] Smart context assembly from structured data
- [ ] OR logic support for requirements: `[["A", "B"], ["C"]]`
- [ ] Character relationship processing
- [ ] Performance optimization and caching
- [ ] Flag mechanics (items, transitions, completion_flags)

### Phase 3: Migration Tools (1 week)
- [ ] Story conversion tools from v1 to v3 format
- [ ] Validation tools for v3 stories
- [ ] Testing framework for both engines
- [ ] Documentation and migration guides

### Phase 4: Rollout (1 week)
- [ ] Beta testing with v3 example stories
- [ ] Full migration with fallback support
- [ ] Legacy system removal
- [ ] Performance monitoring

### New Format Structure
```yaml
# 6 core sections only:
story_context: |
  One-paragraph narrative foundation

characters:
  character_id:
    name: "Name"
    traits: ["trait", "list"]
    arc: "development trajectory"
    relationships:
      other_char: "relationship description"

moments:
  moment_id:
    text: "Player experience"
    goals: ["Natural language goals"]
    transitions:
      - to: "next_moment"
        when: "natural condition"
        sets_flags: ["flags"]

world:
  locations: { }
  items: { }

endings:
  impromptu:
    enabled: true
    signal: "IMPROMPTU_ENDING"
  variations: { }

hints: |
  Universal LLM guidance
```

### Impromptu Endings
Key innovation allowing LLM to signal natural story conclusions:
```typescript
class ImpromptuEndingDetector {
  checkForImpromptuEnding(response: string): ImpromptuEnding | null {
    // Detect signal and handle emergent conclusions
  }
}
```

### For Authors
- **90% fewer lines** to write equivalent stories
- **5 concepts** to learn instead of 20+
- **Natural language** throughout - no technical syntax
- **LLM-friendly** - AI tools can generate stories

### For Players  
- **Pure conversational interface** - no jarring basic commands
- **Emergent story conclusions** handle unexpected developments
- **Consistent narrative voice** through LLM-first processing

### For Codebase
- **80% simpler architecture** - remove complex state machines
- **Better performance** - streamlined processing
- **Context efficiency** - structured data assembly
- **Easier maintenance** - fewer moving parts

## Example Stories

Three v3 format examples are available in `examples/future/`:
- `coffee_confessional_v3_claude.yaml` - Intimate conversation (150→40 lines, 73% reduction)
- `sandwich_crisis_v3_claude.yaml` - Comedy with item transformations  
- `sentient_quill_v3_claude.yaml` - Victorian mystery with character arcs

## Risk Mitigation

- **Feature flags** enable safe parallel development
- **Conversion tools** automatically migrate existing stories
- **Fallback system** maintains current functionality during transition
- **Comprehensive testing** with existing story library

## Success Criteria

- [ ] All existing stories can be converted to v3 format
- [ ] v3 stories demonstrate equivalent or better narrative quality
- [ ] 90% reduction in story authoring complexity achieved
- [ ] Performance improvements measurable
- [ ] Smooth migration path with zero downtime

## References

- **Proposal**: `docs/proposals/narrative-engine-v3.md`
- **Example Stories**: `examples/future/*_v3_claude.yaml`
- **Supersedes**: format-v2.md, dialogue-v2.md, dialogue-v3.md proposals

This represents the most significant architecture change in Iffy Engine history - transforming from a complex state machine to an elegant LLM-guided storytelling system.
