### ISSUE TITLE
Allow per-scene LLM guidance

### ISSUE THREAD

**Issue by indraastra** [indraastra/iffy#28]
## Problem

Currently, Iffy stories only support global guidance that applies to all scenes. This limits the ability to provide specific instructions for different parts of a story that may require different LLM behavior.

## Proposed Solution

Add support for scene-specific guidance that gets included in the LLM prompt when the player is in that scene.

### Example Use Cases

1. **Different interaction styles per scene**:
   - Opening scene: "Be mysterious and atmospheric" 
   - Combat scene: "Be direct and action-focused"
   - Romance scene: "Focus on emotional nuance"

2. **Technical requirements per scene**:
   - Investigation scene: "Always mention available evidence when player asks to examine"
   - Puzzle scene: "Give hints if player seems stuck for 3+ attempts"
   - Dialogue scene: "Track character mood and adjust responses accordingly"

3. **Transition-specific behavior**:
   - Scene with complex endings: "Be extra careful about ending conditions"
   - Scene with many transitions: "Don't rush through transitions"

### Proposed YAML Format

```yaml
scenes:
  - id: "investigation"
    sketch: |
      You examine the crime scene...
    guidance: |
      Focus on forensic details. Always mention what evidence is available 
      when the player tries to examine something. Be methodical and logical.
    leads_to:
      confrontation: "player has gathered enough evidence"
      
  - id: "confrontation" 
    sketch: |
      You face the suspect...
    guidance: |
      This is the climactic scene. Build tension through dialogue.
      Let the player present evidence piece by piece.
```

### Implementation Notes

- Scene guidance should be **added to** (not replace) global guidance
- Prompt structure: Global guidance + Current scene guidance (if present)
- Should work with both single-scene and multi-scene stories
- Backwards compatible - stories without scene guidance continue to work

### Benefits

- More precise LLM control for complex stories
- Better separation of concerns (global vs scene-specific behavior)
- Enables more sophisticated storytelling techniques
- Maintains story quality across different scene types

This would be particularly valuable for stories like The Sentient Quill where different scenes (investigation vs interrogation vs deduction) need different LLM approaches.
