### ISSUE TITLE
Allow stories to directly add memories to the memory system

### ISSUE THREAD

**Issue by indraastra** [indraastra/iffy#30]
### Summary
Stories should be able to directly add memories to the memory system, not just rely on LLM-generated memories from interactions.

### Current Behavior
Currently, memories are only added through:
1. LLM responses that include a `memories` array in their JSON output
2. Item discovery through the `reveals` field
3. Automatic scene transition tracking

### Proposed Enhancement
Stories should be able to define memories that get added directly when certain conditions are met, without requiring LLM interpretation.

### Use Cases

**1. Scene-Based Memory Addition**
```yaml
scenes:
  library_entrance:
    sketch: "You enter the ancient library..."
    memories:
      - "entered the forbidden library"
      - "first glimpse of the vast collection"
```

**2. Conditional Memory Addition**
```yaml
scenes:
  revelation_scene:
    sketch: "The truth becomes clear..."
    memories:
      when: "player has gathered all clues"
      add: 
        - "solved the mystery of the missing heir"
        - "discovered the family secret"
```

**3. Choice-Based Memory Addition**
```yaml
scenes:
  moral_choice:
    sketch: "You must decide..."
    memories:
      choices:
        save_village: ["chose to save innocent lives", "sacrificed personal gain for others"]
        take_treasure: ["chose personal wealth", "abandoned the village to its fate"]
```

### Benefits

1. **Deterministic Memory Control**: Authors can ensure specific memories are added at key story moments
2. **Narrative Consistency**: Important plot points are guaranteed to be remembered
3. **Reduced LLM Dependency**: Critical story state doesn't rely on LLM memory generation
4. **Enhanced Story Structure**: Authors can explicitly define what should be memorable

### Technical Implementation

Add support in:
- `ImpressionistScene` interface for memory definitions
- Parser to handle memory field parsing
- Engine to process and add memories when scenes are entered
- Memory system to accept direct additions from story definitions

### Example Integration

```yaml
title: "The Heist"
# ... other story fields

scenes:
  planning_phase:
    sketch: "You gather your crew in the safehouse..."
    memories:
      - "assembled the heist team"
      - "learned about the bank's security system"
    leads_to:
      execution: "when the plan is finalized"
      
  execution:
    sketch: "The heist begins at midnight..."
    memories:
      when: "heist_successful"
      add: ["successfully robbed the bank", "became a master criminal"]
    leads_to:
      escape: "when the vault is cracked"
```

This would complement the existing LLM-generated memories while giving authors direct control over key narrative moments.

### Priority
Medium - This would significantly improve story author control over narrative memory without breaking existing functionality.
