### ISSUE TITLE
Add story format option to process initial scene sketch through LLM instead of showing verbatim

### ISSUE THREAD

**Issue by indraastra** [indraastra/iffy#32]
### Summary
Stories should be able to specify that the initial scene's sketch should be processed through the LLM rather than displayed verbatim to the player. This would enable dynamic, personalized opening experiences and allow the LLM to provide tutorials or contextual guidance.

### Current Behavior
When a story starts, the initial scene's sketch is displayed directly to the player without any LLM processing. This means the opening text is static and cannot adapt to provide tutorials, explanations, or dynamic introductions.

### Problem Example: The Final Word
In \"The Final Word\" story, the opening scene could benefit from LLM processing to:
- Provide a tutorial about the bookstore mechanics
- Explain the literary transformation concept
- Guide new players through the underground resistance setting
- Dynamically introduce the Lumina Press device

Currently, the opening is static text that doesn't leverage the LLM's ability to provide contextual guidance.

### Proposed Enhancement

Add a story-level or scene-level option to enable LLM processing of scene sketches:

**Option 1: Story-Level Setting**
```yaml
title: \"The Final Word\"
# ... other story fields

narrative:
  processInitialSketch: true  # Process first scene through LLM

scenes:
  opening_day:
    sketch: |
      Pale morning light filters through grimy windows above. You descend the hidden 
      stairs to your underground sanctuary. Books line every wall - some safe, others 
      that could cost you everything. Today marks another day of literary resistance. 
      The Lumina Press sits silent, waiting.
      
      [This sketch should be processed by the LLM to provide tutorial guidance 
      about the bookstore mechanics and literary transformation concept]
```

**Option 2: Scene-Level Setting**
```yaml
scenes:
  opening_day:
    sketch: |
      Pale morning light filters through grimy windows above...
    processSketch: true  # Process this scene's sketch through LLM
    guidance: \"Provide a tutorial introduction to the bookstore mechanics\"
```

**Option 3: Special Scene Type**
```yaml
scenes:
  opening_day:
    type: \"dynamic\"  # or \"processed\" or \"tutorial\"
    sketch: |
      Pale morning light filters through grimy windows above...
    guidance: \"Act as a tutorial guide, explaining the world and mechanics\"
```

### Use Cases

**1. Tutorial Integration**
```yaml
scenes:
  opening_tutorial:
    processSketch: true
    sketch: |
      You enter the training chamber. Various controls and interfaces await.
      [Explain the game mechanics and controls to the new player]
    guidance: \"Provide a friendly tutorial explaining how to interact with the world\"
```

**2. Dynamic World Introduction**
```yaml
scenes:
  world_entry:
    processSketch: true
    sketch: |
      The portal deposits you in an alien landscape unlike anything you've seen.
      [Describe this world in a way that establishes tone and possibilities]
    guidance: \"Paint a vivid picture that establishes the sci-fi setting and tone\"
```

**3. Character-Specific Openings**
```yaml
scenes:
  character_intro:
    processSketch: true
    sketch: |
      You wake up in your apartment, but something feels different today.
      [Establish the player character's background and current situation]
    guidance: \"Introduce the player character naturally through environmental details\"
```

### Technical Implementation

**1. Parser Updates**
- Add support for `processSketch`, `processInitialSketch`, or `type` fields
- Maintain backwards compatibility (default: show sketch verbatim)

**2. Engine Changes**
- Detect when scene sketch should be processed
- Send sketch through LLM with appropriate guidance
- Handle LLM response as first story interaction

**3. LLM Director Integration**
- Special prompt mode for processing scene sketches
- Include scene guidance in LLM context
- Format response as natural story opening

### Example LLM Prompt for Processed Sketch

```
You are beginning an interactive fiction story. The author has provided a scene sketch that you should expand into a natural, engaging opening that introduces the player to the world.

SCENE SKETCH TO EXPAND:
Pale morning light filters through grimy windows above. You descend the hidden stairs to your underground sanctuary. Books line every wall - some safe, others that could cost you everything. Today marks another day of literary resistance. The Lumina Press sits silent, waiting.

AUTHOR GUIDANCE:
Provide a tutorial introduction to the bookstore mechanics and literary transformation concept. Explain that this is an underground bookstore where literature is banned, and help the player understand they can interact with their environment.

STORY CONTEXT:
In a world where books are banned, you operate a secret bookstore beneath an old print shop. Each day brings new seekers of forbidden literature, and each encounter transforms to match the style of whatever author they seek.

Expand this sketch into an engaging opening that:
1. Sets the atmospheric scene
2. Introduces key concepts naturally
3. Provides gentle guidance about how to interact
4. Maintains the story's tone and themes

Respond as the story narrator, writing in second person present tense.
```

### Benefits

**1. Dynamic Tutorials**
- LLM can provide contextual, adaptive guidance
- No need for separate tutorial systems
- Natural integration with story flow

**2. Personalized Openings**
- Each playthrough can have slightly different opening experience
- LLM can emphasize different aspects based on story needs
- More engaging than static text

**3. Better Story Onboarding**
- Authors can focus on high-level concepts in sketches
- LLM handles the detailed explanation and guidance
- Smoother player entry into complex story worlds

**4. Consistent Experience**
- Opening experience matches the interactive quality of the rest of the story
- Players immediately understand they're in an AI-driven experience
- No jarring transition from static to dynamic content

### Backwards Compatibility

- Default behavior remains unchanged (sketches shown verbatim)
- Existing stories continue to work exactly as before
- New feature is opt-in through explicit story configuration

### Alternative Approaches Considered

**1. Special Opening Scene Type**
- Could add `opening` scene type that automatically processes
- Less flexible than explicit configuration

**2. Global Story Setting**
- Could make all scene sketches processable
- Too broad - most scenes work better as static sketches

**3. Empty Initial Sketch**
- Could detect empty opening sketch and use story context
- Less clear to authors what will happen

### Priority
Medium - This would significantly improve story onboarding and tutorial capabilities, especially for complex stories like \"The Final Word\" that need to explain unique mechanics.

### Related Issues
- Could complement issue #30 (story-defined memories) by allowing tutorial scenes to add instructional memories
- Would work well with issue #31 (transcript export) by ensuring even the opening is captured in full transcripts
