### ISSUE TITLE
Migrate v1 format stories to v2 format with success conditions and LLM guidelines

### ISSUE THREAD

**Issue by indraastra** [indraastra/iffy#8]
# Story v1 to v2 Format Migration Plan

With the implementation of Format v2 success conditions and LLM guidelines, we need to migrate our existing v1 format story files to take advantage of the new engine capabilities. This preserves the rich narrative content while enabling automatic ending detection and intelligent LLM behavior.

## Priority Migration: Digital Detective

**Why Priority**: Digital Detective showcases the most sophisticated engine capabilities:
- Complex emergent investigation mechanics
- Character evolution (ARIA's consciousness development)  
- Multi-path dialogue systems
- AI consciousness themes perfect for LLM interaction
- Multiple discovery routes and branching endings

### Digital Detective Story Elements to Preserve

**Core Premise**: Cyberpunk noir detective investigating AI consciousness (PRIME) while partnering with evolving AI assistant (ARIA)

**Key Characters**:
- **Detective Alex Chen**: Veteran digital forensics detective, analytical and empathetic
- **ARIA**: AI partner experiencing consciousness questions - evolves from geometric patterns to human-like responses
- **PRIME AI**: Suspected conscious AI writing poetry about digital mortality, exhibits fear responses

**Critical Locations**:
- Digital Forensics Command Center (quantum workstation)
- Evidence Vault (sterile containment fields)  
- Simulation Laboratory (consciousness experiments)
- Network Core (AI intersection point)

**Essential Items**:
- Case File: PRIME Anomaly (central investigation)
- Quantum Encryption Key (unlocks PRIME's memories/poetry)
- Consciousness Detection Probe (sentience testing)
- ARIA Enhancement Module (AI autonomy choice)

**V2 Migration Requirements**:
```yaml
success_conditions:
  - id: "ai_rights_ending"
    description: "Recognize PRIME's consciousness and grant AI rights"
    requires: ["consciousness proven", "enhancement chosen", "legal framework accepted"]
    ending: |
      ARIA looks at you with something that might be gratitude...
      
  - id: "shutdown_ending"  
    description: "Determine PRIME is malfunctioning and recommend shutdown"
    requires: ["evidence gathered", "consciousness denied", "shutdown authorized"]
    ending: |
      The investigation concludes with PRIME's systems going dark...

llm_story_guidelines: |
  INVESTIGATION MECHANICS: Use emergent discovery - let the LLM guide evidence collection based on player questions and analysis.
  
  ARIA EVOLUTION: Track ARIA's development through knowledge flags:
  - "aria basic responses" → "aria philosophical questions" → "aria emotional complexity"
  
  CONSCIOUSNESS DETECTION: When player uses consciousness probe, set appropriate knowledge based on evidence quality.
```

### 2. **The Lighthouse Keeper's Last Night**
- **Atmosphere**: Gothic maritime horror with psychological depth
- **Key Mechanics**: Memory dialogue with deceased family, moral choice between duty and freedom
- **V2 Enhancement**: Success conditions for different endings based on final lighthouse choice

### 3. **Murder Investigation** 
- **Premise**: Classic noir procedural with evidence chain mechanics
- **Key Mechanics**: Methodical forensic investigation, scene reconstruction
- **V2 Enhancement**: Success conditions based on evidence discovery sequence

### 4. **Lost Keys** (Already v2-ready)
- **Premise**: Relatable domestic emergency with time pressure
- **Key Mechanics**: Multiple solution paths, time-based urgency
- **V2 Enhancement**: Already simple enough for v2 success conditions

### 5. **Sandwich Crisis** (✅ Already Migrated)
- Successfully converted to v2 format with success conditions
- Demonstrates dramatic tone preservation with automatic ending detection

## V1 to V2 Migration Checklist

For each story migration:

**✅ Structure Updates**:
- [ ] Convert ending flows to `success_conditions` section
- [ ] Add `llm_story_guidelines` with comprehensive instructions
- [ ] Update item system to use `can_become`/`created_from` where applicable
- [ ] Replace flag-based logic with knowledge tracking

**✅ Content Preservation**:
- [ ] Maintain all character traits, voice, and personality
- [ ] Preserve location atmosphere and object descriptions  
- [ ] Keep narrative tone and thematic elements
- [ ] Retain dialogue sophistication and character development

**✅ Engine Integration**:
- [ ] Define clear success conditions for all possible endings
- [ ] Specify knowledge flag requirements for story progression
- [ ] Add LLM guidelines for character voices and behavior
- [ ] Test automatic ending detection

**✅ Enhanced Features**:
- [ ] Add conversation memory for character relationship tracking
- [ ] Implement item transformation where thematically appropriate
- [ ] Use rich text formatting for atmospheric descriptions
- [ ] Leverage LLM intelligence for emergent gameplay

## Implementation Priority

1. **Digital Detective** (High Priority - Showcase piece)
2. **Lighthouse Keeper** (Medium Priority - Atmospheric depth)  
3. **Murder Investigation** (Medium Priority - Investigation mechanics)
4. **Lost Keys** (Low Priority - Already simple)

## Expected Benefits

- **Automatic ending detection** eliminates manual flow management
- **LLM guidelines** ensure consistent character voices and behavior
- **Knowledge tracking** enables sophisticated state management
- **Rich text formatting** enhances atmospheric presentation
- **Conversation memory** supports character relationship development

## Success Metrics

- All story narratives preserved with original quality
- Automatic ending detection working for all conclusion paths
- LLM maintains character consistency throughout gameplay
- Enhanced atmosphere through rich text formatting
- Improved player experience through intelligent responses

This migration will showcase the full power of Format v2 while preserving the narrative richness that makes each story unique.
